import type { Asset, Budget, Category, Transaction } from './lunchmoney';

export const DEMO_CATEGORIES: Category[] = [
    {
        id: 101,
        name: '401k Contribution',
        description: null,
        is_income: false,
        exclude_from_budget: false,
        exclude_from_totals: false,
        updated_at: '2024-01-01T00:00:00Z',
        created_at: '2024-01-01T00:00:00Z',
        is_group: false,
        group_id: null,
        order: 1,
    },
    {
        id: 102,
        name: 'Roth IRA',
        description: null,
        is_income: false,
        exclude_from_budget: false,
        exclude_from_totals: false,
        updated_at: '2024-01-01T00:00:00Z',
        created_at: '2024-01-01T00:00:00Z',
        is_group: false,
        group_id: null,
        order: 2,
    },
    {
        id: 103,
        name: 'Groceries',
        description: null,
        is_income: false,
        exclude_from_budget: false,
        exclude_from_totals: false,
        updated_at: '2024-01-01T00:00:00Z',
        created_at: '2024-01-01T00:00:00Z',
        is_group: false,
        group_id: null,
        order: 3,
    },
];

export const DEMO_ASSETS: Asset[] = [
    {
        id: 1,
        name: 'Main Checking',
        balance: '12500.50',
        type_name: 'cash',
        subtype_name: 'checking',
        balance_as_of: '2024-01-01T00:00:00Z',
        currency: 'usd',
        institution_name: 'Demo Bank',
        created_at: '2024-01-01T00:00:00Z',
        is_plaid: false,
    },
    {
        id: 2,
        name: 'Tech 401k',
        balance: '450000.00',
        type_name: 'investment',
        subtype_name: '401k',
        balance_as_of: '2024-01-01T00:00:00Z',
        currency: 'usd',
        institution_name: 'Demo Investments',
        created_at: '2024-01-01T00:00:00Z',
        is_plaid: false,
    },
    {
        id: 3,
        name: 'Growth Roth IRA',
        balance: '185000.00',
        type_name: 'investment',
        subtype_name: 'roth',
        balance_as_of: '2024-01-01T00:00:00Z',
        currency: 'usd',
        institution_name: 'Demo Investments',
        created_at: '2024-01-01T00:00:00Z',
        is_plaid: false,
    },
    {
        id: 4,
        name: 'Brokerage (VTSAX)',
        balance: '320000.00',
        type_name: 'investment',
        subtype_name: 'brokerage',
        balance_as_of: '2024-01-01T00:00:00Z',
        currency: 'usd',
        institution_name: 'Demo Brokerage',
        created_at: '2024-01-01T00:00:00Z',
        is_plaid: false,
    },
];

export const DEMO_BUDGETS: Budget[] = [
    {
        category_id: 103,
        category_name: 'Groceries',
        category_group_name: null,
        is_income: false,
        exclude_from_budget: false,
        exclude_from_totals: false,
        amount: '600',
        currency: 'usd',
        spent: '450',
    },
    {
        category_id: 104,
        category_name: 'Rent',
        category_group_name: null,
        is_income: false,
        exclude_from_budget: false,
        exclude_from_totals: false,
        amount: '2000',
        currency: 'usd',
        spent: '2000',
    },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
    {
        id: 1,
        date: '2024-11-01',
        payee: '401k Payroll Deduction',
        amount: '1500.00',
        currency: 'usd',
        category_id: 101,
        asset_id: 1,
        plaid_account_id: null,
        status: 'reviewed',
    },
    {
        id: 2,
        date: '2024-11-15',
        payee: 'Grocery Store',
        amount: '125.50',
        currency: 'usd',
        category_id: 103,
        asset_id: 1,
        plaid_account_id: null,
        status: 'reviewed',
    },
    {
        id: 3,
        date: '2024-11-20',
        payee: 'Employer Paycheck',
        amount: '-8500.00',
        currency: 'usd',
        category_id: null,
        asset_id: 1,
        plaid_account_id: null,
        status: 'reviewed',
    },
];

export function getDemoData() {
    return {
        assets: DEMO_ASSETS,
        transactions: DEMO_TRANSACTIONS,
        budgets: DEMO_BUDGETS,
        categories: DEMO_CATEGORIES,
    };
}
